language: generic
sudo: required
services:
- docker
script:
- docker build -t therickys93/wikirediscommander .
after_success:
- if [ "$TRAVIS_BRANCH" == "master" ] && [ "$TRAVIS_PULL_REQUEST" == "false" ]; then
  docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"; docker push therickys93/wikirediscommander;
  fi
